python_test:
  - 'authmodules/apache2/**/*.py'
  - 'tests/**'
  - 'tools/**'
  - 'privacyidea/**/*.py'
  - '.github/workflows/python.yml'
  - '.github/filters.yml'
  - 'pi-manage'
  - 'requirements.txt'
  - 'setup.py'
