jobs:
  build:
    docker:
      - image: circleci/mysql:latest-ram
        environment:
          MYSQL_DATABASE: pi
          MYSQL_USER: pi
          MYSQL_PASSWORD: test123
          MYSQL_RANDOM_ROOT_PASSWORD: yes
    environment:
      TEST_DATABASE_URL: mysql+pymysql://pi:test123@localhost/pi
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - python/install-packages:
          pip-dependency-file: tests/requirements.txt
          pkg-manager: pip
      - run:
          command: |
            python -b -m pytest --cov=privacyidea tests/
          name: Test

orbs:
  python: circleci/python@1.1.0

version: 2.1
workflows:
  main:
    jobs:
      - build
