# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip installation
      uses: actions/cache@v2
      id: venv-cache
      with:
        path: |
          ~/.cache/pip
          ~/venv
        key: ${{ runner.os }}-pip-py_${{ matrix.python-version }}-${{ hashFiles('requirements.txt', 'tests/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-py_${{ matrix.python-version }}-
          ${{ runner.os }}-pip-

    - name: Install venv for Python 2.7
      run: |
        pip install py2venv
      if: matrix.python-version == '2.7'

    - name: Install dependencies
      run: |
        python -m venv ~/venv && . ~/venv/bin/activate
        python -m pip install --upgrade pip setuptools
        pip install -r tests/requirements.txt
      if: steps.venv-cache.outputs.cache-hit != 'true'

    - name: Test with pytest
      run: |
        . ~/venv/bin/activate
        python -b -m pytest -v --cov=privacyidea tests/

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-${{ matrix.python-version }}
        path: ./.coverage
        retention-days: 1

  finish:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code for coverage
      uses: actions/checkout@v2
    - name: Cache pip installation
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-coverage }}
        restore-keys: |
          ${{ runner.os }}-pip-coverage
          ${{ runner.os }}-pip-

    - name: Install coverage for merging output 
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install coverage
        echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Download coverage report artifacts
      uses: actions/download-artifact@v2
      with:
        path: ./cov_reports

    - name: Combine coverage reports
      working-directory: ./cov_reports
      run: |
        coverage combine coverage-*/.coverage
        coverage xml

    - name: Codecov upload
      uses: codecov/codecov-action@v1
      with:
        file: ./cov_reports/coverage.xml

