# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['2.7', '3.5', '3.9']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip installation
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-py_${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-py_${{ matrix.python-version }}-
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r tests/requirements.txt
       
    - name: Test with pytest
      run: |
        python -b -m pytest -v --cov=privacyidea --cov-report= tests

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-${{ matrix.python-version }}
        path: ~/.coverage
        retention-days: 1

  finish:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - name: Cache pip installation
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-coverage }}
        restore-keys: |
          ${{ runner.os }}-pip-coverage
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install coverage
    - name: Download coverage report artifacts
      uses: actions/download-artifact@v2
      with:
        path: cov_reports
    - name: Combine coverage reports
      run: |
        coverage combine cov_reports/*
        coverage xml
    - name: Codecov upload
      uses: codecov/codecov-action@v1
      with:
        file: ~/coverage.xml

