name: reviewdog-codespell
on:
  pull_request:

jobs:
  codespell:
    name: runner / codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: codespell
        uses: plettich/action-codespell@master
        with:
          reporter: github-pr-review
          level: info
