name: reviewdog-codespell
on:
  pull_request:

jobs:
  reviewdog-github-check:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: reviewdog (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install codespell
        run: |
          python -m pip install -U codespell

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          codespell -q 3 -S ./privacyidea/static/contrib/*,translations.js,*.po -L assertIn . \
          | reviewdog -efm="%f:%l: %m" -name="codespell" -reporter=github-pr-check -level=warning
