name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.reviewdog_secret }}
        with:
#          github_token: ${{ secrets.reviewdog_secret }}
          reporter: github-pr-review
          level: info

