name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: "./privacyidea/static/contrib/*, ./privacyidea/static/components/translation/*, ./privacyidea/translations/*, ./po/*"
